version: '3.7'

services:
  server:
    build:
      context: ./back-end
      dockerfile: Dockerfile
    image: myapp-server
    container_name: back-end
    command: /node_modules/.bin/nodemon server.js
    volumes:
      - ./back-end/:/app
      - /node_modules
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    env_file: ./back-end/.env
    environment:
      - NODE_ENV=development
    networks:
      - app-network
  mongo:
    image: mongo
    volumes:
      - data-volume:/data/db
    ports:
      - "27017:27017"
    networks:
      - app-network
  client:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    image: myapp-client
    container_name: front-end
    command: npm start
    volumes:
      - ./front-end/:/usr/app
      - /usr/app/node_modules
    depends_on:
      - server
    ports:
      - "4000:4000"
    networks:
      - app-network

networks:
    app-network:
        driver: bridge

volumes:
    data-volume:
    node_modules:
    web-root:
      driver: local